//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddantSDAL.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AddantEntities1 : DbContext
    {
        public AddantEntities1()
            : base("name=AddantEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PositionDetail> PositionDetails { get; set; }
        public virtual DbSet<EmbedCode> EmbedCodes { get; set; }
        public virtual DbSet<EmbedCodeType> EmbedCodeTypes { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<TemplateType> TemplateTypes { get; set; }
        public virtual DbSet<AddantLifeDetail> AddantLifeDetails { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Enquiry> Enquiries { get; set; }
        public virtual DbSet<EnquiryCategory> EnquiryCategories { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<OTPHistory> OTPHistories { get; set; }
        public virtual DbSet<AddantLife> AddantLives { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserPrivilege> UserPrivileges { get; set; }
        public virtual DbSet<EventCategory> EventCategories { get; set; }
    }
}
