//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddantSDAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddantLifeDetail
    {
        public int IdAddantLifeImage { get; set; }
        public Nullable<int> IdAddantLife { get; set; }
        public string InnerCaption { get; set; }
        public string InnerImageUrl { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual AddantLife AddantLife { get; set; }
    }
}
