//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddantSDAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int IdBlog { get; set; }
        public string ConverImgUrl { get; set; }
        public string BannerImgUrl { get; set; }
        public string ContentUrl { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string MainHeader { get; set; }
        public string HeaderDescription { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> MinReadTime { get; set; }
        public string ProfilePicUrl { get; set; }
        public string BlogContent { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
