//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddantSDAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionDetail
    {
        public int IdPositionDetail { get; set; }
        public Nullable<int> IdPosition { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string SubHeader { get; set; }
        public string SubHeaderContent { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
