//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddantSDAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPrivilege
    {
        public int IdUserPrivilege { get; set; }
        public Nullable<bool> CreatePage { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> ViewPage { get; set; }
        public Nullable<bool> DisablePage { get; set; }
        public Nullable<int> IdPage { get; set; }
        public Nullable<int> IdUserRole { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> StatusPage { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
